INSERT INTO waste_type(name) VALUES ('Metale i tworzywa sztuczne');
INSERT INTO WASTE_TYPE(NAME) VALUES ('Szkło');
INSERT INTO WASTE_TYPE(NAME) VALUES ('Papier');
INSERT INTO WASTE_TYPE(NAME) VALUES ('Bio');
INSERT INTO WASTE_TYPE(NAME) VALUES ('Zmieszane');


INSERT INTO WASTE(NAME, WASTE_TYPE_ID) VALUES ('plastikowa butelka', 1);
INSERT INTO WASTE(NAME, WASTE_TYPE_ID) VALUES ('puszka aluminiowa', 1);
INSERT INTO WASTE(NAME, WASTE_TYPE_ID) VALUES ('styropian', 1);
INSERT INTO WASTE(NAME, WASTE_TYPE_ID) VALUES ('szklana butelka', 2);
INSERT INTO WASTE(NAME, WASTE_TYPE_ID) VALUES ('słoik', 2);
INSERT INTO WASTE(NAME, WASTE_TYPE_ID) VALUES ('papierowe opakowanie', 3);
INSERT INTO WASTE(NAME, WASTE_TYPE_ID) VALUES ('książka telefoniczna', 3);
INSERT INTO WASTE(NAME, WASTE_TYPE_ID) VALUES ('ulotki', 3);
INSERT INTO WASTE(NAME, WASTE_TYPE_ID) VALUES ('kartony po napojach', 3);
INSERT INTO WASTE(NAME, WASTE_TYPE_ID) VALUES ('skórka banana', 4);
INSERT INTO WASTE(NAME, WASTE_TYPE_ID) VALUES ('obierki ziemniaka', 4);
INSERT INTO WASTE(NAME, WASTE_TYPE_ID) VALUES ('obierki marchewki', 4);
INSERT INTO WASTE(NAME, WASTE_TYPE_ID) VALUES ('porcelana', 5);
INSERT INTO WASTE(NAME, WASTE_TYPE_ID) VALUES ('pieluchy jednorazowe', 5);
INSERT INTO WASTE(NAME, WASTE_TYPE_ID) VALUES ('kurz z odkurzacza', 5);